apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: $APP_INSTANCE_NAME-rabbitmq-metrics-exporter
  labels: &RabbitMQDeploymentLabels
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: rabbitmq-metrics-exporter
spec:
  selector:
    matchLabels: *RabbitMQDeploymentLabels
  replicas: 1
  template:
    metadata:
      labels: *RabbitMQDeploymentLabels
    spec:
      containers:
      - name: rabbitmq-prometheus-metrics
        image: gcr.io/google-containers/prometheus-to-sd:v0.3.2
        ports:
        - name: profiler
          containerPort: 6060
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=$APP_INSTANCE_NAME:http://$APP_INSTANCE_NAME-rabbitmq-svc:15672/api/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --scrape-interval=5s
          - --export-interval=30s
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

